backend:
  name: git-gateway
  branch: main
logo_url: /assets/images/logo.png
locale: 'pt'
media_folder: "assets/images" 

collections:
  - name: "conditions"
    label: Conditions
    folder: "_conditions"
    create: true
    slug: "{{header_title}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "conditions"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Header Title", name: "header_title", widget: "string"}
      - {label: "Header Button Text", name: "header_button_text", widget: "string"}
      - {label: "Header Image", name: "header_image", widget: "image"}      
      - {label: "Short Description", name: "short_description", widget: "markdown"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Content", name: "content", widget: "markdown"}
      - {label: "Keywords", name: "keywords", widget: "string"}
  - name: "pages"
    label: Pages
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/"}
          - {label: "Header Background Image", name: "header_background_image", widget: "image" }
  - name: 'settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Settings'
        file: '_data/settings.json'
        description: 'General Site Settings'
        fields:
          - { label: 'Global title', name: 'site_title', widget: 'string' }
          - label: 'Post Settings'
            name: posts
            widget: 'object'
            fields:
              - {
                  label: 'Number of posts on frontpage',
                  name: front_limit,
                  widget: number,
                  min: 1,
                  max: 10,
                }
              - { label: 'Default Author', name: author, widget: string }
              - {
                  label: 'Default Thumbnail',
                  name: thumb,
                  widget: image,
                  class: 'thumb',
                  required: false,
                }
